### ISSUE TITLE
pcrfit_single error when l4 model is not calculated

### ISSUE THREAD

**Issue by kablag** [PCRuniversum/PCRedux#6]
pcrfit_single gives error on data without amp
(columns 70, 183, 331 in provided file [test.txt](https://github.com/PCRuniversum/PCRedux/files/3783029/test.txt))
```
tbl <- read.csv("test.txt")[-1]
pcrfit_single(tbl[,70])

Error in if (names(res_fit_model) == "l4") res_fit <- pcrfit_model_l4 : 
  argument is of length zero
```

**Comment by devSJR** [comment]
thanks for spotting an reporting. fixed in 4e9490853fd7f1a57e0f1f93bd806e369e714741
