### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by markziemann** [PCRuniversum/PCRedux#9]
One of the JOSS checklist items is Community guidelines. If allowed by CRAN, please create a CONTRIBUTING file in the repository that provides clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support.
https://github.com/openjournals/joss-reviews/issues/4407

**Comment by markziemann** [comment]
Great! A brief guide on how users should report bugs and request features is required.

**Comment by devSJR** [comment]
True. I will add that now.

**Comment by markziemann** [comment]
Perfect
